version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.10.cli-migrations-v3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    volumes: 
     - ./hasura/migrations:/hasura-migrations
     - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  frontend:
    depends_on:
    - "graphql-engine"
    ports:
      - 3000:3000
    build:
      context: ./metallurgy-frontend
      dockerfile: Dockerfile.dev
    environment:
      # Note - these are in the environment for DEV, but need to be in the build.args for production
      - HASURA_HTTP_URL=http://graphql-engine:8080/v1/graphql
      - HASURA_WSS_URL=wss://graphql-engine:8080/v1/graphql
    volumes:
      - ./metallurgy-frontend:/usr/src/app
      - /usr/src/app/node_modules
      # - /usr/src/app/.next
    # env_file:
    #   - ../metallurgy-frontend/.env
volumes:
  db_data:

